# CodeRabbit Configuration
# https://docs.coderabbit.ai/guides/configure-coderabbit

language: en
reviews:
  auto_review:
    enabled: true
  path_instructions:
    - path: "src/**/*.py"
      instructions: "Review for Python best practices, type hints, and security issues"
    - path: "tests/**/*.py"
      instructions: "Ensure tests are comprehensive and follow pytest conventions"
